networks:
    1panel-network:
        external: true
services:
    mysql:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        image: cikiche:fastadmin
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:80
        restart: always
        volumes:
            - ./conf/my.cnf:/etc/nginx/sites-enabled/
            - ./log:/var/www/html
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
version: "3"
