version: '3'

services:
  fastadmin:
    image: fastadmin:latest
    container_name: fastadmin
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./conf/my.cnf:/etc/nginx/sites-enabled/
      - ./log:/var/www/html
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      