version: "3"
networks:
    1panel-network:
        external: true
services:
    fastadmin:
        container_name: fastadmin
        image: ./dockerfile
        networks:
            - 1panel-network
        ports:
            - 80:80
        restart: always
        volumes:
            - ./conf/my.cnf:/etc/nginx/sites-enabled/
            - ./log:/var/www/html
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
